# Generated by Django 5.0 on 2025-11-12 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre del Rol"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UsuarioPersonalizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "correo",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo Electrónico"
                    ),
                ),
                ("nombre", models.CharField(max_length=30, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=30, verbose_name="Apellido")),
                (
                    "es_staff",
                    models.BooleanField(default=False, verbose_name="Es Staff"),
                ),
                (
                    "es_superusuario",
                    models.BooleanField(default=False, verbose_name="Es Superusuario"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="Users.rol",
                        verbose_name="Rol",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "permissions": [
                    ("can_receive_monthly_report", "Puede recibir reporte mensual"),
                    ("can_create_subject", "Puede crear asignaturas"),
                    ("can_grade_task", "Puede calificar tareas"),
                    ("can_view_analytics", "Puede ver reportes analíticos"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TokenRecuperacionContraseña",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("usado", models.BooleanField(default=False, verbose_name="Usado")),
                ("expira_el", models.DateTimeField(verbose_name="Expira el")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens_recuperacion",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Recuperación",
                "verbose_name_plural": "Tokens de Recuperación",
            },
        ),
    ]
