# Generated by Django 5.0 on 2025-11-14 15:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodoAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "nombre",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nombre del periodo"
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de fin")),
            ],
            options={
                "verbose_name": "Periodo académico",
                "verbose_name_plural": "Periodos académicos",
                "db_table": "periodo_academico",
            },
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "archivo_entrega",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="entregas/",
                        verbose_name="Archivo de entrega",
                    ),
                ),
                (
                    "comentarios_estudiante",
                    models.TextField(
                        blank=True, null=True, verbose_name="Comentarios del estudiante"
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de entrega"
                    ),
                ),
                (
                    "estado_entrega",
                    models.CharField(
                        choices=[
                            ("P", "Pendiente"),
                            ("E", "Entregada"),
                            ("C", "Calificada"),
                        ],
                        default="P",
                        max_length=1,
                        verbose_name="Estado de la entrega",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega",
                "verbose_name_plural": "Entregas",
                "db_table": "entrega",
            },
        ),
        migrations.CreateModel(
            name="Calificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Nota"
                    ),
                ),
                (
                    "retroalimentacion_docente",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Retroalimentación del docente",
                    ),
                ),
                (
                    "fecha_calificacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de calificación"
                    ),
                ),
                (
                    "entrega",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calificacion",
                        to="Academicos.entrega",
                        verbose_name="Entrega",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calificación",
                "verbose_name_plural": "Calificaciones",
                "db_table": "calificacion",
            },
        ),
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la asignatura"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Código de la asignatura",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "docente_responsable",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"groups__name": "Docente"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asignaturas_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Docente responsable",
                    ),
                ),
                (
                    "periodo_academico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaturas",
                        to="Academicos.periodoacademico",
                        verbose_name="Periodo académico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignatura",
                "verbose_name_plural": "Asignaturas",
                "db_table": "asignatura",
            },
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "titulo",
                    models.CharField(max_length=100, verbose_name="Título de la tarea"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "fecha_publicacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de publicación",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateTimeField(verbose_name="Fecha de vencimiento"),
                ),
                (
                    "peso_porcentual",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peso porcentual"
                    ),
                ),
                (
                    "tipo_tarea",
                    models.CharField(
                        choices=[("T", "Tarea"), ("E", "Examen")],
                        default="T",
                        max_length=1,
                        verbose_name="Tipo de tarea",
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to="Academicos.asignatura",
                        verbose_name="Asignatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
                "db_table": "tarea",
            },
        ),
        migrations.AddField(
            model_name="entrega",
            name="tarea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entregas",
                to="Academicos.tarea",
                verbose_name="Tarea",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entrega",
            unique_together={("tarea", "estudiante")},
        ),
    ]
