# Generated by Django 5.0 on 2025-11-18 23:53

import Academicos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Academicos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignatura",
            name="codigo",
            field=models.CharField(
                default=Academicos.models.generar_codigo_unico,
                editable=False,
                max_length=8,
                unique=True,
                verbose_name="Codigo Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="entrega",
            name="estado_entrega",
            field=models.CharField(
                choices=[("P", "Pendiente"), ("E", "Entregada"), ("C", "Calificada")],
                default="E",
                max_length=1,
                verbose_name="Estado de la entrega",
            ),
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "fecha_inscripcion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de inscripción"
                    ),
                ),
                (
                    "estado_inscripcion",
                    models.CharField(
                        choices=[
                            ("A", "Activa"),
                            ("R", "Retirada"),
                            ("S", "Suspendida"),
                        ],
                        default="A",
                        max_length=1,
                        verbose_name="estado de la inscripción",
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones_asignatura",
                        to="Academicos.asignatura",
                        verbose_name="asignatura",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Estudiante"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones_estudiante",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscripción",
                "verbose_name_plural": "inscripciones",
                "db_table": "inscripcion",
                "permissions": [
                    ("puede_inscribirse", "Puede inscribirse a asignaturas"),
                    ("puede_ver_inscripciones", "Puede ver todas las inscripciones"),
                ],
                "unique_together": {("estudiante", "asignatura")},
            },
        ),
    ]
