"""
Django settings for Edupro360 project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from __future__ import absolute_import, unicode_literals

import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# Clave secreta para registro de admin
ADMIN_REGISTRATION_SECRET = os.getenv('ADMIN_REGISTRATION_SECRET')
ADMIN_REGISTRATION_ENABLED = os.getenv('ADMIN_REGISTRATION_ENABLED', 'False').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-default-key") 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# ANTES (falla en producción)
if not ADMIN_REGISTRATION_SECRET:
    raise ValueError("ADMIN_REGISTRATION_SECRET es obligatorio en .env")

# AHORA (perfecto para Render)
if not ADMIN_REGISTRATION_SECRET and DEBUG:
    raise ValueError("ADMIN_REGISTRATION_SECRET es obligatorio en .env (solo en desarrollo)")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")

# === CONFIGURACIÓN DE CORREO ELECTRÓNICO ===
EMAIL_USER = os.getenv('EMAIL_USER')
EMAIL_PASS = os.getenv('EMAIL_PASS')

if DEBUG:
    # vemos el correo en consola 
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Producción o pruebas reales
    if EMAIL_USER and EMAIL_PASS:
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        EMAIL_HOST = 'smtp.gmail.com'
        EMAIL_PORT = 587
        EMAIL_USE_TLS = True
        EMAIL_HOST_USER = EMAIL_USER
        EMAIL_HOST_PASSWORD = EMAIL_PASS
        DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
        SERVER_EMAIL = EMAIL_HOST_USER
        print("Correo configurado para envío REAL con Gmail")
    else:
        # Seguridad: si no hay credenciales → no envía y no muestra nada en consola
        EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
        print("ATENCIÓN: No hay credenciales de correo → envío desactivado")

# URL del frontend (para correos, redirecciones, etc.)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5174')

# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_celery_beat',
    'django_celery_results',
]

LOCAL_APPS = [
    "Base",
    "Usuarios",
    "Notificaciones",
    "Academicos",
]

THIRD_PARTY_APPS = [
    'corsheaders',
    'drf_yasg',
    'rest_framework',
    'rest_framework_simplejwt',
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_PARTY_APPS

AUTH_USER_MODEL = 'Usuarios.Usuario'

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Edupro360.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Edupro360.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
        "default": {
            "ENGINE": os.getenv("DB_ENGINE"),
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "es-co"
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS AUTORIZATIONS
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
]

REST_FRAMEWORK = {
    # === AUTENTICACIÓN ===
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],

    # === PERMISOS GLOBALES ===
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Requiere login por defecto
    ],

    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),

    # === THROTTLING (RATE LIMITING) ===
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',     # Para usuarios no autenticados
        'rest_framework.throttling.UserRateThrottle',     # Para usuarios autenticados
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/min',      # 10 peticiones por minuto
        'user': '100/min',     # 100 peticiones por minuto para usuarios logueados
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("ACCESS_TOKEN_LIFETIME", 60))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("REFRESH_TOKEN_LIFETIME", 7))),
    'ROTATE_REFRESH_TOKENS': False,
}

# CELERY

if os.getenv('RENDER') or os.getenv('RAILWAY') or not os.getenv('DEBUG') == 'True':
    # Producción → usar Redis Cloud
    CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
    CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
else:
    # Local Windows → usar Redis local
    CELERY_BROKER_URL = 'redis://localhost:6379/0'
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'



# SWAGGER

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'Token de acceso. Ejemplo: Bearer eyJhbGciOiJIUzI1NiIsIn...'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'patch', 'delete'],
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'list',
    'SHOW_COMMON_EXTENSIONS': True,
}

# Para que aparezcan TODOS los endpoints (incluso los de AllowAny)
DEFAULT_AUTO_SCHEMA_CLASS = 'drf_yasg.inspectors.SwaggerAutoSchema'


# settings.py → CONFIGURACIÓN CON R2 PRIVADO
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')

# CLAVE PARA R2 PRIVADO
AWS_S3_REGION_NAME = 'auto'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE = 'path'        
AWS_S3_USE_SSL = True

# SEGURIDAD
AWS_QUERYSTRING_AUTH = True
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_EXPIRE = 3600
AWS_S3_FILE_OVERWRITE = True


