# Generated by Django 5.0 on 2025-11-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "cedula",
                    models.CharField(
                        help_text="Cédula de identidad o documento único",
                        max_length=20,
                        unique=True,
                        verbose_name="Cédula",
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo Electrónico"
                    ),
                ),
                ("nombres", models.CharField(max_length=50, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=50, verbose_name="Apellidos"),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=10,
                        null=True,
                        verbose_name="Género",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Código de Usuario",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Nacimiento"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "telefono_emergencia",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Teléfono de Emergencia",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "reset_password_token",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "reset_password_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Es Staff"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="Es Superusuario"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Esta activado"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "permissions": [
                    ("can_receive_monthly_report", "Puede recibir reporte mensual"),
                    ("can_grade_task", "Puede calificar tareas"),
                    ("can_view_analytics", "Puede ver reportes analíticos"),
                    ("can_view_own_grades", "Puede ver sus propias calificaciones"),
                    ("can_view_own_tasks", "Puede ver sus tareas"),
                    ("can_submit_task", "Puede entregar tareas"),
                ],
                "indexes": [
                    models.Index(
                        fields=["correo"], name="Usuarios_us_correo_951587_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="Usuarios_us_is_acti_5dd65b_idx"
                    ),
                ],
            },
        ),
    ]
