# Generated by Django 5.0 on 2025-11-13 17:46

import Usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="codigo",
            field=models.CharField(
                default=Usuarios.models.generar_codigo_unico,
                editable=False,
                max_length=8,
                unique=True,
                verbose_name="Codigo Usuario",
            ),
        ),
    ]
